 MODULE mod_chem_spack_kinetic
  
   IMPLICIT NONE
   PRIVATE
   PUBLIC :: kinetic ! subroutine
 CONTAINS
   SUBROUTINE kinetic(jppj,Jphoto,rk,temp,xlw,Press,cosz,att,ijkbeg,ijkend,maxblock_size,nr)
 
!------------------------------------------------------------------------
!
!     -- DESCRIPTION
!
!     This routine computes the kinetic rates for the gas-phase.
!     This routine is automatically generated by SPACK.
!     Mechanism: ../Mechanism/RELACS 
!     Species: ../Mechanism/ciRCSH5
!
!------------------------------------------------------------------------
!
!     -- INPUT VARIABLES
!
!     TEMP: temperature ([K]).
!     XLW: water massic fraction.
!     PRESS: pressure ([Pa]).
!     AZI: zenithal angle ([degree]).
!     ATT: attenuation variable.
!
!     -- INPUT/OUTPUT VARIABLES
!
!     -- OUTPUT VARIABLES
!
!     RK: kinetic rates.
!
!------------------------------------------------------------------------
!
!     -- REMARKS
!
!------------------------------------------------------------------------
!
!     -- MODIFICATIONS
!
!------------------------------------------------------------------------
!
!     -- AUTHOR(S)
!
!     SPACK.
!
!------------------------------------------------------------------------
 
      IMPLICIT NONE
 
 
 
      INTEGER,INTENT(IN) :: jppj,ijkbeg,ijkend,maxblock_size,nr
      DOUBLE PRECISION,INTENT(IN) ::  xlw(maxblock_size),att(maxblock_size),cosz(maxblock_size)
      DOUBLE PRECISION,INTENT(IN) ::  temp(maxblock_size),Press(maxblock_size)
      DOUBLE PRECISION,INTENT(OUT) ::  rk(maxblock_size,nr)
      DOUBLE PRECISION,DIMENSION(maxblock_size) ::  Effko,Rapk,facteur
      DOUBLE PRECISION,DIMENSION(maxblock_size) :: YlH2O,SumM,azi
      DOUBLE PRECISION,INTENT(IN) ::  Jphoto(maxblock_size,jppj)
      INTEGER :: ijk
 
!     Compute third body.
!     Conversion = Avogadro*1d-6/Perfect gas constant.
!     PRESS in Pascal, SUMM in molecules/cm3, TEMP in Kelvin
 
      DO ijk=ijkbeg,ijkend
        SumM(ijk) = Press(ijk) * 7.243D16 / temp(ijk)
      END DO
 
!     Number of water molecules computed from the massic fraction
!     (absolute humidity)
 
      DO ijk=ijkbeg,ijkend
         YlH2O(ijk) = 29.d0*SumM(ijk)*xlw(ijk)/(18.d0+11.d0*xlw(ijk))
      END DO
 
!     For the zenithal angle at tropics
 
      azi=abs(acos(cosz)*180.0/3.1415926) !From cosz obtain angle azi in degrees
 
 
       DO ijk=ijkbeg,ijkend
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  1)=-0.1302720567168789D-07
       rk(ijk,  1)=-0.7822279432831316D-06+(azi(ijk)- 0.00D+00) * rk(ijk,  1)
       rk(ijk,  1)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  1)
       rk(ijk,  1)= 0.9310260000000001D-02+(azi(ijk)- 0.00D+00) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  1)= 0.3771617015066953D-08
       rk(ijk,  1)=-0.1173044113433769D-05+(azi(ijk)- 0.10D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1955272056716900D-04+(azi(ijk)- 0.10D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.9219010000000000D-02+(azi(ijk)- 0.10D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  1)=-0.5859262388581603D-08
       rk(ijk,  1)=-0.1059895602981760D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.4188211773132429D-04+(azi(ijk)- 0.20D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.8909950000000000D-02+(azi(ijk)- 0.20D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  1)=-0.7024567460739109D-08
       rk(ijk,  1)=-0.1235673474639209D-05+(azi(ijk)- 0.30D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.6483780850753396D-04+(azi(ijk)- 0.30D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.8379279999999999D-02+(azi(ijk)- 0.30D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  1)=-0.9202467768463278D-08
       rk(ijk,  1)=-0.1446410498461379D-05+(azi(ijk)- 0.40D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.9165864823853988D-04+(azi(ijk)- 0.40D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.7600310000000000D-02+(azi(ijk)- 0.40D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  1)=-0.1612556146541203D-07
       rk(ijk,  1)=-0.1722484531515246D-05+(azi(ijk)- 0.50D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1233475985383064D-03+(azi(ijk)- 0.50D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.6529880000000000D-02+(azi(ijk)- 0.50D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  1)= 0.3226471363012407D-07
       rk(ijk,  1)=-0.2206251375477739D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1626349576082347D-03+(azi(ijk)- 0.60D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.5108030000000000D-02+(azi(ijk)- 0.60D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  1)= 0.2027078243960391D-06
       rk(ijk,  1)=-0.1238309966574421D-05+(azi(ijk)- 0.70D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1970805710287534D-03+(azi(ijk)- 0.70D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.3293320000000000D-02+(azi(ijk)- 0.70D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  1)=-0.7448311471175039D-07
       rk(ijk,  1)= 0.3626677818932096D-05+(azi(ijk)- 0.78D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1779736282099075D-03+(azi(ijk)- 0.78D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.1741210000000000D-02+(azi(ijk)- 0.78D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  1)= 0.2490309929267239D-05
       rk(ijk,  1)= 0.1839083065847241D-05+(azi(ijk)- 0.86D+02) * rk(ijk,  1)
       rk(ijk,  1)=-0.1342475411316550D-03+(azi(ijk)- 0.86D+02) * rk(ijk,  1)
       rk(ijk,  1)= 0.5113930000000000D-03+(azi(ijk)- 0.86D+02) * rk(ijk,  1)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  1)= 0.1632080000000000D-03
      endif
      rk(ijk,  1) = rk(ijk,  1) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  2)=-0.8776629099833420D-10
       rk(ijk,  2)=-0.1165033709001662D-07+(azi(ijk)- 0.00D+00) * rk(ijk,  2)
       rk(ijk,  2)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  2)
       rk(ijk,  2)= 0.3523480000000000D-04+(azi(ijk)- 0.00D+00) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  2)= 0.1474988729949891D-09
       rk(ijk,  2)=-0.1428332581996664D-07+(azi(ijk)- 0.10D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.2593366290998326D-06+(azi(ijk)- 0.10D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.3398200000000000D-04+(azi(ijk)- 0.10D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  2)= 0.1300707990183873D-09
       rk(ijk,  2)=-0.9858359630116980D-08+(azi(ijk)- 0.20D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.5007534836006687D-06+(azi(ijk)- 0.20D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.3010780000000000D-04+(azi(ijk)- 0.20D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  2)= 0.1988179309314557D-09
       rk(ijk,  2)=-0.5956235659565352D-08+(azi(ijk)- 0.30D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.6588994364974921D-06+(azi(ijk)- 0.30D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.2424450000000000D-04+(azi(ijk)- 0.30D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  2)= 0.2219574772557704D-09
       rk(ijk,  2)= 0.8302268378494226D-11+(azi(ijk)- 0.40D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.7183787704093628D-06+(azi(ijk)- 0.40D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.1725870000000000D-04+(azi(ijk)- 0.40D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  2)= 0.1913521600454229D-09
       rk(ijk,  2)= 0.6667026586051454D-08+(azi(ijk)- 0.50D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.6516254818650610D-06+(azi(ijk)- 0.50D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.1029770000000000D-04+(azi(ijk)- 0.50D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  2)= 0.1602388256259833D-10
       rk(ijk,  2)= 0.1240759138741341D-07+(azi(ijk)- 0.60D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.4608793021304060D-06+(azi(ijk)- 0.60D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.4639500000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  2)=-0.3089359890776449D-09
       rk(ijk,  2)= 0.1288830786429022D-07+(azi(ijk)- 0.70D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.2079203096133862D-06+(azi(ijk)- 0.70D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.1287490000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  2)=-0.2034952628702240D-09
       rk(ijk,  2)= 0.5473844126423800D-08+(azi(ijk)- 0.78D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.6102309368774707D-07+(azi(ijk)- 0.78D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.2908040000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  2)= 0.1623544915691508D-09
       rk(ijk,  2)= 0.5899578174960450D-09+(azi(ijk)- 0.86D+02) * rk(ijk,  2)
       rk(ijk,  2)=-0.1251267813614395D-07+(azi(ijk)- 0.86D+02) * rk(ijk,  2)
       rk(ijk,  2)= 0.4875570000000000D-07+(azi(ijk)- 0.86D+02) * rk(ijk,  2)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  2)= 0.1853500000000000D-07
      endif
      rk(ijk,  2) = rk(ijk,  2) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  3)=-0.5928286648808007D-09
       rk(ijk,  3)=-0.3096171335119278D-07+(azi(ijk)- 0.00D+00) * rk(ijk,  3)
       rk(ijk,  3)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  3)
       rk(ijk,  3)= 0.4927580000000000D-03+(azi(ijk)- 0.00D+00) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  3)= 0.1444859946426951D-09
       rk(ijk,  3)=-0.4874657329761681D-07+(azi(ijk)- 0.10D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.7970828664880959D-06+(azi(ijk)- 0.10D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.4890690000000000D-03+(azi(ijk)- 0.10D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  3)=-0.5511531369015992D-10
       rk(ijk,  3)=-0.4441199345833597D-07+(azi(ijk)- 0.20D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.1728668534047624D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.4763680000000000D-03+(azi(ijk)- 0.20D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  3)=-0.3000247398820652D-09
       rk(ijk,  3)=-0.4606545286904076D-07+(azi(ijk)- 0.30D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.2633442997321390D-05+(azi(ijk)- 0.30D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.4545850000000000D-03+(azi(ijk)- 0.30D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  3)=-0.2397857267814825D-09
       rk(ijk,  3)=-0.5506619506550265D-07+(azi(ijk)- 0.40D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.3644759476666825D-05+(azi(ijk)- 0.40D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.4233440000000000D-03+(azi(ijk)- 0.40D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  3)=-0.1844832352992110D-08
       rk(ijk,  3)=-0.6225976686894679D-07+(azi(ijk)- 0.50D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.4818019096011324D-05+(azi(ijk)- 0.50D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.3811500000000000D-03+(azi(ijk)- 0.50D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  3)= 0.1101151387498967D-09
       rk(ijk,  3)=-0.1176047374587144D-06+(azi(ijk)- 0.60D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.6616664139287888D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.3248990000000000D-03+(azi(ijk)- 0.60D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  3)=-0.1557211541864023D-07
       rk(ijk,  3)=-0.1143012832962279D-06+(azi(ijk)- 0.70D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.8935724346837256D-05+(azi(ijk)- 0.70D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.2470820000000000D-03+(azi(ijk)- 0.70D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  3)= 0.4048472604225035D-07
       rk(ijk,  3)=-0.4880320533435654D-06+(azi(ijk)- 0.78D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.1375439103995572D-04+(azi(ijk)- 0.78D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.1603080000000000D-03+(azi(ijk)- 0.78D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  3)= 0.2066880316661520D-06
       rk(ijk,  3)= 0.4836013716701137D-06+(azi(ijk)- 0.86D+02) * rk(ijk,  3)
       rk(ijk,  3)=-0.1378983649333980D-04+(azi(ijk)- 0.86D+02) * rk(ijk,  3)
       rk(ijk,  3)= 0.3976700000000000D-04+(azi(ijk)- 0.86D+02) * rk(ijk,  3)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  3)= 0.5573310000000000D-05
      endif
      rk(ijk,  3) = rk(ijk,  3) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  4)=-0.2887225450832654D-08
       rk(ijk,  4)=-0.1810277454916759D-06+(azi(ijk)- 0.00D+00) * rk(ijk,  4)
       rk(ijk,  4)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  4)
       rk(ijk,  4)= 0.2046710000000000D-02+(azi(ijk)- 0.00D+00) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  4)= 0.8216763524985514D-09
       rk(ijk,  4)=-0.2676445090166556D-06+(azi(ijk)- 0.10D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.4486722545083314D-05+(azi(ijk)- 0.10D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.2025720000000000D-02+(azi(ijk)- 0.10D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  4)=-0.1309479959161345D-08
       rk(ijk,  4)=-0.2429942184416991D-06+(azi(ijk)- 0.20D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.9593109819666860D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1954910000000000D-02+(azi(ijk)- 0.20D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  4)=-0.1523756515853734D-08
       rk(ijk,  4)=-0.2822786172165392D-06+(azi(ijk)- 0.30D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.1484583817624924D-04+(azi(ijk)- 0.30D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1833370000000000D-02+(azi(ijk)- 0.30D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  4)=-0.1745493977423840D-08
       rk(ijk,  4)=-0.3279913126921493D-06+(azi(ijk)- 0.40D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.2094853747533615D-04+(azi(ijk)- 0.40D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1655160000000000D-02+(azi(ijk)- 0.40D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  4)=-0.2754267574452238D-08
       rk(ijk,  4)=-0.3803561320148585D-06+(azi(ijk)- 0.50D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.2803201192240627D-04+(azi(ijk)- 0.50D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1411130000000000D-02+(azi(ijk)- 0.50D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  4)= 0.1037656427522960D-07
       rk(ijk,  4)=-0.4629841592484437D-06+(azi(ijk)- 0.60D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.3646541483503906D-04+(azi(ijk)- 0.60D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1090020000000000D-02+(azi(ijk)- 0.60D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  4)= 0.4335158727144718D-07
       rk(ijk,  4)=-0.1516872309916274D-06+(azi(ijk)- 0.70D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.4261212873743960D-04+(azi(ijk)- 0.70D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.6894440000000000D-03+(azi(ijk)- 0.70D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  4)=-0.2976581610935105D-07
       rk(ijk,  4)= 0.8887508635231610D-06+(azi(ijk)- 0.78D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.3671561967718845D-04+(azi(ijk)- 0.78D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.3610350000000000D-03+(azi(ijk)- 0.78D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  4)= 0.5586598403877321D-06
       rk(ijk,  4)= 0.1743712768980777D-06+(azi(ijk)- 0.86D+02) * rk(ijk,  4)
       rk(ijk,  4)=-0.2821064255380800D-04+(azi(ijk)- 0.86D+02) * rk(ijk,  4)
       rk(ijk,  4)= 0.1089500000000000D-03+(azi(ijk)- 0.86D+02) * rk(ijk,  4)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  4)= 0.3465160000000000D-04
      endif
      rk(ijk,  4) = rk(ijk,  4) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  5)=-0.1532025548735493D-11
       rk(ijk,  5)=-0.1605297445126457D-09+(azi(ijk)- 0.00D+00) * rk(ijk,  5)
       rk(ijk,  5)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  5)
       rk(ijk,  5)= 0.7475310000000001D-06+(azi(ijk)- 0.00D+00) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  5)= 0.1499076646206643D-11
       rk(ijk,  5)=-0.2064905109747105D-09+(azi(ijk)- 0.10D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.3670202554873561D-08+(azi(ijk)- 0.10D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.7299460000000000D-06+(azi(ijk)- 0.10D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  5)= 0.8827189639089452D-12
       rk(ijk,  5)=-0.1615182115885113D-09+(azi(ijk)- 0.20D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.7350289780505779D-08+(azi(ijk)- 0.20D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.6740940000000000D-06+(azi(ijk)- 0.20D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  5)= 0.1742047498157467D-11
       rk(ijk,  5)=-0.1350366426712434D-09+(azi(ijk)- 0.30D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.1031583832310332D-07+(azi(ijk)- 0.30D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.5853220000000000D-06+(azi(ijk)- 0.30D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  5)= 0.2513091043461019D-11
       rk(ijk,  5)=-0.8277521772651680D-10+(azi(ijk)- 0.40D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.1249395692708095D-07+(azi(ijk)- 0.40D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.4704020000000000D-06+(azi(ijk)- 0.40D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  5)= 0.3194588327999034D-11
       rk(ijk,  5)=-0.7382486422686429D-11+(azi(ijk)- 0.50D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.1339553396857297D-07+(azi(ijk)- 0.50D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.3396980000000000D-06+(azi(ijk)- 0.50D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  5)= 0.5281855644544062D-11
       rk(ijk,  5)= 0.8845516341725539D-10+(azi(ijk)- 0.60D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.1258480719862693D-07+(azi(ijk)- 0.60D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.2081990000000000D-06+(azi(ijk)- 0.60D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  5)=-0.2756160173518845D-12
       rk(ijk,  5)= 0.2469108327535101D-09+(azi(ijk)- 0.70D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.9231147236918914D-08+(azi(ijk)- 0.70D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.9647830000000000D-07+(azi(ijk)- 0.70D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  5)=-0.5270116382857717D-11
       rk(ijk,  5)= 0.2402960483371050D-09+(azi(ijk)- 0.78D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.5333492188196593D-08+(azi(ijk)- 0.78D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.3829030000000000D-07+(azi(ijk)- 0.78D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  5)= 0.3312732748143745D-10
       rk(ijk,  5)= 0.1138132551483600D-09+(azi(ijk)- 0.86D+02) * rk(ijk,  5)
       rk(ijk,  5)=-0.2500617760306919D-08+(azi(ijk)- 0.86D+02) * rk(ijk,  5)
       rk(ijk,  5)= 0.8303010000000000D-08+(azi(ijk)- 0.86D+02) * rk(ijk,  5)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  5)= 0.2241700000000000D-08
      endif
      rk(ijk,  5) = rk(ijk,  5) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  6)=-0.1022637521258295D-10
       rk(ijk,  6)=-0.1047636247874169D-08+(azi(ijk)- 0.00D+00) * rk(ijk,  6)
       rk(ijk,  6)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  6)
       rk(ijk,  6)= 0.5038360000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  6)= 0.9289125637748354D-11
       rk(ijk,  6)=-0.1354427504251658D-08+(azi(ijk)- 0.10D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.2402063752125827D-07+(azi(ijk)- 0.10D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.4923370000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  6)= 0.4979872661590801D-11
       rk(ijk,  6)=-0.1075753735119208D-08+(azi(ijk)- 0.20D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.4832244991496693D-07+(azi(ijk)- 0.20D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.4557010000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  6)= 0.1055138371588663D-10
       rk(ijk,  6)=-0.9263575552714857D-09+(azi(ijk)- 0.30D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.6834356281887383D-07+(azi(ijk)- 0.30D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.3971190000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  6)= 0.1620459247486142D-10
       rk(ijk,  6)=-0.6098160437948826D-09+(azi(ijk)- 0.40D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.8370529880953758D-07+(azi(ijk)- 0.40D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.3205670000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  6)= 0.2215024638466714D-10
       rk(ijk,  6)=-0.1236782695490249D-09+(azi(ijk)- 0.50D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.9104024194297691D-07+(azi(ijk)- 0.50D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.2323840000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  6)= 0.3999042198646269D-10
       rk(ijk,  6)= 0.5408291219909645D-09+(azi(ijk)- 0.60D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.8686873341855749D-07+(azi(ijk)- 0.60D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.1423220000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  6)=-0.2067341716793420D-11
       rk(ijk,  6)= 0.1740541781584667D-08+(azi(ijk)- 0.70D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.6405502438280023D-07+(azi(ijk)- 0.70D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.6486060000000000D-06+(azi(ijk)- 0.70D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  6)=-0.2916729149970486D-10
       rk(ijk,  6)= 0.1690925580381730D-08+(azi(ijk)- 0.78D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.3660328548706694D-07+(azi(ijk)- 0.78D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.2465020000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  6)= 0.1504439894566837D-09
       rk(ijk,  6)= 0.9909105843816125D-09+(azi(ijk)- 0.86D+02) * rk(ijk,  6)
       rk(ijk,  6)=-0.1514859616887210D-07+(azi(ijk)- 0.86D+02) * rk(ijk,  6)
       rk(ijk,  6)= 0.4696130000000000D-07+(azi(ijk)- 0.86D+02) * rk(ijk,  6)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  6)= 0.1184990000000000D-07
      endif
      rk(ijk,  6) = rk(ijk,  6) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  7)=-0.3691161034363460D-07
       rk(ijk,  7)=-0.1177883896563626D-05+(azi(ijk)- 0.00D+00) * rk(ijk,  7)
       rk(ijk,  7)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  7)
       rk(ijk,  7)= 0.2656490000000000D-01+(azi(ijk)- 0.00D+00) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  7)= 0.1703483103089474D-07
       rk(ijk,  7)=-0.2285232206872664D-05+(azi(ijk)- 0.10D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.3463116103436289D-04+(azi(ijk)- 0.10D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2641020000000000D-01+(azi(ijk)- 0.10D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  7)=-0.1532771377994151D-07
       rk(ijk,  7)=-0.1774187275945823D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.7522535586254776D-04+(azi(ijk)- 0.20D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2585240000000000D-01+(azi(ijk)- 0.20D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  7)=-0.1372397591112777D-07
       rk(ijk,  7)=-0.2234018689344070D-05+(azi(ijk)- 0.30D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.1153074155154467D-03+(azi(ijk)- 0.30D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2490740000000000D-01+(azi(ijk)- 0.30D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  7)=-0.2747638257554609D-07
       rk(ijk,  7)=-0.2645737966677890D-05+(azi(ijk)- 0.40D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.1641049820756664D-03+(azi(ijk)- 0.40D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2351720000000000D-01+(azi(ijk)- 0.40D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  7)=-0.1322704937866908D-06
       rk(ijk,  7)=-0.3470029443944269D-05+(azi(ijk)- 0.50D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.2252626561818881D-03+(azi(ijk)- 0.50D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2158410000000000D-01+(azi(ijk)- 0.50D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  7)=-0.2304164227770285D-07
       rk(ijk,  7)=-0.7438144257545083D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.3343443931967814D-03+(azi(ijk)- 0.60D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.1885220000000000D-01+(azi(ijk)- 0.60D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  7)=-0.1151055949406269D-05
       rk(ijk,  7)=-0.8129393525876153D-05+(azi(ijk)- 0.70D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.4900197710309918D-03+(azi(ijk)- 0.70D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.1474190000000000D-01+(azi(ijk)- 0.70D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  7)= 0.3051007034750409D-05
       rk(ijk,  7)=-0.3575473631162467D-04+(azi(ijk)- 0.78D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.8410928097310252D-03+(azi(ijk)- 0.78D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.9712119999999999D-02+(azi(ijk)- 0.78D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  7)= 0.1099207874720812D-04
       rk(ijk,  7)= 0.3746943252237739D-04+(azi(ijk)- 0.86D+02) * rk(ijk,  7)
       rk(ijk,  7)=-0.8273752400449071D-03+(azi(ijk)- 0.86D+02) * rk(ijk,  7)
       rk(ijk,  7)= 0.2257190000000000D-02+(azi(ijk)- 0.86D+02) * rk(ijk,  7)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  7)= 0.2506930000000000D-03
      endif
      rk(ijk,  7) = rk(ijk,  7) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  8)=-0.1926445199576596D-06
       rk(ijk,  8)=-0.1114355480042343D-04+(azi(ijk)- 0.00D+00) * rk(ijk,  8)
       rk(ijk,  8)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  8)
       rk(ijk,  8)= 0.2129960000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  8)=-0.3806644012699886D-07
       rk(ijk,  8)=-0.1692289039915322D-04+(azi(ijk)- 0.10D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.2806644519957665D-03+(azi(ijk)- 0.10D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.2116890000000000D+00+(azi(ijk)- 0.10D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  8)= 0.3591028046562472D-07
       rk(ijk,  8)=-0.1806488360296319D-04+(azi(ijk)- 0.20D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.6305421920169306D-03+(azi(ijk)- 0.20D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.2071520000000000D+00+(azi(ijk)- 0.20D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  8)=-0.2185746817355059D-06
       rk(ijk,  8)=-0.1698757518899445D-04+(azi(ijk)- 0.30D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.9810667799365067D-03+(azi(ijk)- 0.30D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1990760000000000D+00+(azi(ijk)- 0.30D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  8)=-0.2006115535235708D-06
       rk(ijk,  8)=-0.2354481564105945D-04+(azi(ijk)- 0.40D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.1386390688237047D-02+(azi(ijk)- 0.40D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1873480000000000D+00+(azi(ijk)- 0.40D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  8)=-0.1055979104170286D-05
       rk(ijk,  8)=-0.2956316224676663D-04+(azi(ijk)- 0.50D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.1917470467115308D-02+(azi(ijk)- 0.50D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1709290000000000D+00+(azi(ijk)- 0.50D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  8)=-0.3204720297952648D-06
       rk(ijk,  8)=-0.6124253537187633D-04+(azi(ijk)- 0.60D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.2825527443301725D-02+(azi(ijk)- 0.60D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1477420000000000D+00+(azi(ijk)- 0.60D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  8)=-0.6785572971816661D-05
       rk(ijk,  8)=-0.7085669626573617D-04+(azi(ijk)- 0.70D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.4146519759677833D-02+(azi(ijk)- 0.70D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1130420000000000D+00+(azi(ijk)- 0.70D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  8)= 0.2349184361302091D-04
       rk(ijk,  8)=-0.2337104475893259D-03+(azi(ijk)- 0.78D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.6583056910518562D-02+(azi(ijk)- 0.78D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.7186080000000000D-01+(azi(ijk)- 0.78D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  8)= 0.6606749385961857D-04
       rk(ijk,  8)= 0.3300937991231632D-03+(azi(ijk)- 0.86D+02) * rk(ijk,  8)
       rk(ijk,  8)=-0.5811990098247437D-02+(azi(ijk)- 0.86D+02) * rk(ijk,  8)
       rk(ijk,  8)= 0.1626670000000000D-01+(azi(ijk)- 0.86D+02) * rk(ijk,  8)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  8)= 0.2528560000000000D-02
      endif
      rk(ijk,  8) = rk(ijk,  8) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk,  9)=-0.1441479345432036D-10
       rk(ijk,  9)=-0.1242452065456794D-08+(azi(ijk)- 0.00D+00) * rk(ijk,  9)
       rk(ijk,  9)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk,  9)
       rk(ijk,  9)= 0.8394580000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk,  9)= 0.8244380362960527D-11
       rk(ijk,  9)=-0.1674895869086406D-08+(azi(ijk)- 0.10D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.2917347934543199D-07+(azi(ijk)- 0.10D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.8255920000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk,  9)= 0.1172720024782291D-12
       rk(ijk,  9)=-0.1427564458197590D-08+(azi(ijk)- 0.20D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.6019808261827194D-07+(azi(ijk)- 0.20D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.7804940000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk,  9)= 0.4506531627126779D-11
       rk(ijk,  9)=-0.1424046298123243D-08+(azi(ijk)- 0.30D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.8871419018148029D-07+(azi(ijk)- 0.30D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.7060320000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk,  9)= 0.1086660148901067D-10
       rk(ijk,  9)=-0.1288850349309422D-08+(azi(ijk)- 0.40D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.1158431566558071D-06+(azi(ijk)- 0.40D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.6035280000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk,  9)= 0.1803706241682997D-10
       rk(ijk,  9)=-0.9628523046390844D-09+(azi(ijk)- 0.50D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.1383601831952922D-06+(azi(ijk)- 0.50D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.4758830000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk,  9)= 0.7329514884366502D-10
       rk(ijk,  9)=-0.4217404321342295D-09+(azi(ijk)- 0.60D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.1522061105630245D-06+(azi(ijk)- 0.60D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.3296980000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk,  9)= 0.6172011386261483D-10
       rk(ijk,  9)= 0.1777114033175403D-08+(azi(ijk)- 0.70D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.1386523745526125D-06+(azi(ijk)- 0.70D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.1806040000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk,  9)=-0.8279704635718142D-10
       rk(ijk,  9)= 0.3258396765879289D-08+(azi(ijk)- 0.78D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.9836828816018174D-07+(azi(ijk)- 0.78D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.8421570000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk,  9)= 0.1082517324585549D-08
       rk(ijk,  9)= 0.1271267653299030D-08+(azi(ijk)- 0.86D+02) * rk(ijk,  9)
       rk(ijk,  9)=-0.6213097280668286D-07+(azi(ijk)- 0.86D+02) * rk(ijk,  9)
       rk(ijk,  9)= 0.2213560000000000D-06+(azi(ijk)- 0.86D+02) * rk(ijk,  9)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk,  9)= 0.6245350000000000D-07
      endif
      rk(ijk,  9) = rk(ijk,  9) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 10)=-0.7261045436751569D-10
       rk(ijk, 10)=-0.5576895456324840D-08+(azi(ijk)- 0.00D+00) * rk(ijk, 10)
       rk(ijk, 10)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 10)
       rk(ijk, 10)= 0.4669460000000000D-04+(azi(ijk)- 0.00D+00) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 10)= 0.2853136310254520D-10
       rk(ijk, 10)=-0.7755209087350312D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.1333210454367515D-06+(azi(ijk)- 0.10D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.4606430000000000D-04+(azi(ijk)- 0.10D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 10)=-0.1901499804266231D-10
       rk(ijk, 10)=-0.6899268194273959D-08+(azi(ijk)- 0.20D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.2798658182529942D-06+(azi(ijk)- 0.20D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.4398410000000000D-04+(azi(ijk)- 0.20D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 10)=-0.9471370931894209D-11
       rk(ijk, 10)=-0.7469718135553829D-08+(azi(ijk)- 0.30D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.4235556815512720D-06+(azi(ijk)- 0.30D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.4047650000000000D-04+(azi(ijk)- 0.30D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 10)= 0.1440048177021868D-10
       rk(ijk, 10)=-0.7753859263510583D-08+(azi(ijk)- 0.40D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.5757914555419167D-06+(azi(ijk)- 0.40D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.3548450000000000D-04+(azi(ijk)- 0.40D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 10)= 0.3856944385102582D-10
       rk(ijk, 10)=-0.7321844810403943D-08+(azi(ijk)- 0.50D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.7265484962810631D-06+(azi(ijk)- 0.50D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.2896560000000000D-04+(azi(ijk)- 0.50D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 10)= 0.4136217428256926D-09
       rk(ijk, 10)=-0.6164761494873299D-08+(azi(ijk)- 0.60D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.8614145593338335D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.2100650000000000D-04+(azi(ijk)- 0.60D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 10)= 0.5376701572565394D-09
       rk(ijk, 10)= 0.6243890789895679D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.8606232663835842D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.1218950000000000D-04+(azi(ijk)- 0.70D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 10)=-0.5508273900085886D-09
       rk(ijk, 10)= 0.1914797456405770D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.6574883435519911D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.5979410000000000D-05+(azi(ijk)- 0.78D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 10)= 0.8530305662040679D-08
       rk(ijk, 10)= 0.5928117203844831D-08+(azi(ijk)- 0.86D+02) * rk(ijk, 10)
       rk(ijk, 10)=-0.4568796094084461D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 10)
       rk(ijk, 10)= 0.1662950000000000D-05+(azi(ijk)- 0.86D+02) * rk(ijk, 10)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 10)= 0.4762210000000000D-06
      endif
      rk(ijk, 10) = rk(ijk, 10) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 11)=-0.5816837387219485D-10
       rk(ijk, 11)=-0.5184316261278090D-08+(azi(ijk)- 0.00D+00) * rk(ijk, 11)
       rk(ijk, 11)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 11)
       rk(ijk, 11)= 0.3220560000000000D-04+(azi(ijk)- 0.00D+00) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 11)= 0.3450512161659926D-10
       rk(ijk, 11)=-0.6929367477443936D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.1211368373872203D-06+(azi(ijk)- 0.10D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.3162900000000000D-04+(azi(ijk)- 0.10D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 11)= 0.3647887405788254D-11
       rk(ijk, 11)=-0.5894213828945961D-08+(azi(ijk)- 0.20D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.2493726504511192D-06+(azi(ijk)- 0.20D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.2975920000000000D-04+(azi(ijk)- 0.20D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 11)= 0.2530332876024747D-10
       rk(ijk, 11)=-0.5784777206772324D-08+(azi(ijk)- 0.30D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.3661625608083019D-06+(azi(ijk)- 0.30D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.2667970000000000D-04+(azi(ijk)- 0.30D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 11)= 0.6013879755322039D-10
       rk(ijk, 11)=-0.5025677343964817D-08+(azi(ijk)- 0.40D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.4742671063156742D-06+(azi(ijk)- 0.40D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.2246490000000000D-04+(azi(ijk)- 0.40D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 11)= 0.1004414810268224D-09
       rk(ijk, 11)=-0.3221513417368026D-08+(azi(ijk)- 0.50D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.5567390139290039D-06+(azi(ijk)- 0.50D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.1727980000000000D-04+(azi(ijk)- 0.50D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 11)= 0.3107352783395266D-09
       rk(ijk, 11)=-0.2082689865642921D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.5910368379683177D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.1149070000000000D-04+(azi(ijk)- 0.60D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 11)= 0.1345128013864191D-09
       rk(ijk, 11)= 0.9113789363622316D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.5019816341977498D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.5870240000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 11)=-0.1960445509603971D-09
       rk(ijk, 11)= 0.1234209659689431D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.3303345465136462D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.2506540000000000D-05+(azi(ijk)- 0.78D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 11)= 0.2279277828261561D-08
       rk(ijk, 11)= 0.7637027373853022D-08+(azi(ijk)- 0.86D+02) * rk(ijk, 11)
       rk(ijk, 11)=-0.1705015547476910D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 11)
       rk(ijk, 11)= 0.5533830000000000D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 11)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 11)= 0.1394430000000000D-06
      endif
      rk(ijk, 11) = rk(ijk, 11) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 12)=-0.1292568102250474D-10
       rk(ijk, 12)=-0.1349143189774952D-08+(azi(ijk)- 0.00D+00) * rk(ijk, 12)
       rk(ijk, 12)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 12)
       rk(ijk, 12)= 0.6105070000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 12)= 0.1221704306751377D-10
       rk(ijk, 12)=-0.1736913620450095D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.3086056810225046D-07+(azi(ijk)- 0.10D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.5957230000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 12)= 0.7227508752451125D-11
       rk(ijk, 12)=-0.1370402328424683D-08+(azi(ijk)- 0.20D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.6193372759099823D-07+(azi(ijk)- 0.20D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.5487150000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 12)= 0.1521292192267961D-10
       rk(ijk, 12)=-0.1153577065851150D-08+(azi(ijk)- 0.30D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.8717352153375653D-07+(azi(ijk)- 0.30D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.4738000000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 12)= 0.2301080355683157D-10
       rk(ijk, 12)=-0.6971894081707524D-09+(azi(ijk)- 0.40D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.1056811862739757D-06+(azi(ijk)- 0.40D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.3766120000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 12)= 0.3106386384998460D-10
       rk(ijk, 12)=-0.6865301465772937D-11+(azi(ijk)- 0.50D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.1127217333703412D-06+(azi(ijk)- 0.50D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.2662600000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 12)= 0.4531874104323753D-10
       rk(ijk, 12)= 0.9250506140335778D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.1035398802446616D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.1565760000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 12)=-0.1303761111909802D-10
       rk(ijk, 12)= 0.2284612845330262D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.7144324565101817D-07+(azi(ijk)- 0.70D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.6681850000000000D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 12)=-0.4077238230008851D-10
       rk(ijk, 12)= 0.1971710178474831D-08+(azi(ijk)- 0.78D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.3739266146060570D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.2361790000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 12)= 0.1193377495925112D-09
       rk(ijk, 12)= 0.9931730032745764D-09+(azi(ijk)- 0.86D+02) * rk(ijk, 12)
       rk(ijk, 12)=-0.1367359600664033D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 12)
       rk(ijk, 12)= 0.4235170000000000D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 12)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 12)= 0.1118570000000000D-07
      endif
      rk(ijk, 12) = rk(ijk, 12) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 13)=-0.9639086891432947D-11
       rk(ijk, 13)=-0.8144091310856720D-09+(azi(ijk)- 0.00D+00) * rk(ijk, 13)
       rk(ijk, 13)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 13)
       rk(ijk, 13)= 0.5704620000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 13)= 0.5287260674299220D-11
       rk(ijk, 13)=-0.1103581737828661D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.1917990868914333D-07+(azi(ijk)- 0.10D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.5613540000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 13)=-0.2699558057635431D-12
       rk(ijk, 13)=-0.9449639175996847D-09+(azi(ijk)- 0.20D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.3966536524342677D-07+(azi(ijk)- 0.20D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.5316670000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 13)= 0.2382562548753712D-11
       rk(ijk, 13)=-0.9530625917725899D-09+(azi(ijk)- 0.30D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.5864563033714951D-07+(azi(ijk)- 0.30D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.4825250000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 13)= 0.6319705610746925D-11
       rk(ijk, 13)=-0.8815857153099678D-09+(azi(ijk)- 0.40D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.7699211340797518D-07+(azi(ijk)- 0.40D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.4145870000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 13)= 0.1056861500826167D-10
       rk(ijk, 13)=-0.6919945469875617D-09+(azi(ijk)- 0.50D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.9272791603095051D-07+(azi(ijk)- 0.50D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.3294110000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 13)= 0.4850583435617704D-10
       rk(ijk, 13)=-0.3749360967397000D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.1033972224682227D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.2308200000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 13)= 0.4863918163434130D-10
       rk(ijk, 13)= 0.1080238933945261D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.9634419409616384D-07+(azi(ijk)- 0.70D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.1285240000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 13)=-0.6023611040777133D-10
       rk(ijk, 13)= 0.2247579293169346D-08+(azi(ijk)- 0.78D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.6972164827924572D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.6085250000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 13)= 0.8106335758288151D-09
       rk(ijk, 13)= 0.8019126433730944D-09+(azi(ijk)- 0.86D+02) * rk(ijk, 13)
       rk(ijk, 13)=-0.4532571278681815D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 13)
       rk(ijk, 13)= 0.1637560000000000D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 13)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 13)= 0.4716430000000000D-07
      endif
      rk(ijk, 13) = rk(ijk, 13) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 14)=-0.9639086891432947D-11
       rk(ijk, 14)=-0.8144091310856720D-09+(azi(ijk)- 0.00D+00) * rk(ijk, 14)
       rk(ijk, 14)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 14)
       rk(ijk, 14)= 0.5704620000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 14)= 0.5287260674299220D-11
       rk(ijk, 14)=-0.1103581737828661D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.1917990868914333D-07+(azi(ijk)- 0.10D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.5613540000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 14)=-0.2699558057635431D-12
       rk(ijk, 14)=-0.9449639175996847D-09+(azi(ijk)- 0.20D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.3966536524342677D-07+(azi(ijk)- 0.20D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.5316670000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 14)= 0.2382562548753712D-11
       rk(ijk, 14)=-0.9530625917725899D-09+(azi(ijk)- 0.30D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.5864563033714951D-07+(azi(ijk)- 0.30D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.4825250000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 14)= 0.6319705610746925D-11
       rk(ijk, 14)=-0.8815857153099678D-09+(azi(ijk)- 0.40D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.7699211340797518D-07+(azi(ijk)- 0.40D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.4145870000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 14)= 0.1056861500826167D-10
       rk(ijk, 14)=-0.6919945469875617D-09+(azi(ijk)- 0.50D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.9272791603095051D-07+(azi(ijk)- 0.50D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.3294110000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 14)= 0.4850583435617704D-10
       rk(ijk, 14)=-0.3749360967397000D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.1033972224682227D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.2308200000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 14)= 0.4863918163434130D-10
       rk(ijk, 14)= 0.1080238933945261D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.9634419409616384D-07+(azi(ijk)- 0.70D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.1285240000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 14)=-0.6023611040777133D-10
       rk(ijk, 14)= 0.2247579293169346D-08+(azi(ijk)- 0.78D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.6972164827924572D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.6085250000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 14)= 0.8106335758288151D-09
       rk(ijk, 14)= 0.8019126433730944D-09+(azi(ijk)- 0.86D+02) * rk(ijk, 14)
       rk(ijk, 14)=-0.4532571278681815D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 14)
       rk(ijk, 14)= 0.1637560000000000D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 14)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 14)= 0.4716430000000000D-07
      endif
      rk(ijk, 14) = rk(ijk, 14) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 15)=-0.2139600241835142D-11
       rk(ijk, 15)=-0.2151039975816483D-09+(azi(ijk)- 0.00D+00) * rk(ijk, 15)
       rk(ijk, 15)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 15)
       rk(ijk, 15)= 0.1065630000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 15)= 0.1813800725505362D-11
       rk(ijk, 15)=-0.2792920048367027D-09+(azi(ijk)- 0.10D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.4943960024183509D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.1041980000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 15)= 0.9033973398137489D-12
       rk(ijk, 15)=-0.2248779830715419D-09+(azi(ijk)- 0.20D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.9985659903265956D-08+(azi(ijk)- 0.20D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.9664250000000000D-06+(azi(ijk)- 0.20D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 15)= 0.2075609915239581D-11
       rk(ijk, 15)=-0.1977760628771300D-09+(azi(ijk)- 0.30D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.1421220036275267D-07+(azi(ijk)- 0.30D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.8449840000000000D-06+(azi(ijk)- 0.30D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 15)= 0.3345162999228133D-11
       rk(ijk, 15)=-0.1355077654199424D-09+(azi(ijk)- 0.40D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.1754503864572339D-07+(azi(ijk)- 0.40D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.6851600000000000D-06+(azi(ijk)- 0.40D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 15)= 0.4733738087847688D-11
       rk(ijk, 15)=-0.3515287544309787D-10+(azi(ijk)- 0.50D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.1925164505435381D-07+(azi(ijk)- 0.50D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.4995040000000001D-06+(azi(ijk)- 0.50D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 15)= 0.8639884649378068D-11
       rk(ijk, 15)= 0.1068592671923246D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.1853458113686154D-07+(azi(ijk)- 0.60D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.3082060000000000D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 15)=-0.6489929980998621D-13
       rk(ijk, 15)= 0.3660558066736432D-09+(azi(ijk)- 0.70D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.1380543039820209D-07+(azi(ijk)- 0.70D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.1421860000000000D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 15)=-0.7060744231814099D-11
       rk(ijk, 15)= 0.3644982234783992D-09+(azi(ijk)- 0.78D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.7960998156989790D-08+(azi(ijk)- 0.78D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.5513690000000000D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 15)= 0.4009097038577759D-10
       rk(ijk, 15)= 0.1950403619149261D-09+(azi(ijk)- 0.86D+02) * rk(ijk, 15)
       rk(ijk, 15)=-0.3484689473844218D-08+(azi(ijk)- 0.86D+02) * rk(ijk, 15)
       rk(ijk, 15)= 0.1116170000000000D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 15)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 15)= 0.2909410000000000D-08
      endif
      rk(ijk, 15) = rk(ijk, 15) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 16)=-0.4649884923986692D-10
       rk(ijk, 16)=-0.3874011507601324D-08+(azi(ijk)- 0.00D+00) * rk(ijk, 16)
       rk(ijk, 16)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 16)
       rk(ijk, 16)= 0.2781010000000000D-04+(azi(ijk)- 0.00D+00) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 16)= 0.2349654771959695D-10
       rk(ijk, 16)=-0.5268976984797332D-08+(azi(ijk)- 0.10D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.9142988492398655D-07+(azi(ijk)- 0.10D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.2737620000000000D-04+(azi(ijk)- 0.10D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 16)=-0.4087341638516817D-11
       rk(ijk, 16)=-0.4564080553209423D-08+(azi(ijk)- 0.20D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.1897604603040541D-06+(azi(ijk)- 0.20D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.2595850000000000D-04+(azi(ijk)- 0.20D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 16)= 0.8252818834467560D-11
       rk(ijk, 16)=-0.4686700802364927D-08+(azi(ijk)- 0.30D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.2822682738597976D-06+(azi(ijk)- 0.30D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.2360040000000000D-04+(azi(ijk)- 0.30D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 16)= 0.2837606630064206D-10
       rk(ijk, 16)=-0.4439116237330892D-08+(azi(ijk)- 0.40D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.3735264442567558D-06+(azi(ijk)- 0.40D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.2031730000000000D-04+(azi(ijk)- 0.40D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 16)= 0.5284291596297224D-10
       rk(ijk, 16)=-0.3587834248311588D-08+(azi(ijk)- 0.50D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.4537959491131808D-06+(azi(ijk)- 0.50D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.1616650000000000D-04+(azi(ijk)- 0.50D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 16)= 0.2535522698474145D-09
       rk(ijk, 16)=-0.2002546769422965D-08+(azi(ijk)- 0.60D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.5096997592905190D-06+(azi(ijk)- 0.60D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.1132260000000000D-04+(azi(ijk)- 0.60D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 16)= 0.2218412986989881D-09
       rk(ijk, 16)= 0.5604021325997327D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.4736850137247532D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.6278900000000000D-05+(azi(ijk)- 0.70D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 16)=-0.2840497156173424D-09
       rk(ijk, 16)= 0.1092821249477318D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.3414271431586043D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.2961660000000000D-05+(azi(ijk)- 0.78D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 16)= 0.3921356960028698D-08
       rk(ijk, 16)= 0.4111019319929286D-08+(azi(ijk)- 0.86D+02) * rk(ijk, 16)
       rk(ijk, 16)=-0.2211132886405422D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 16)
       rk(ijk, 16)= 0.7842150000000000D-06+(azi(ijk)- 0.86D+02) * rk(ijk, 16)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 16)= 0.2165050000000000D-06
      endif
      rk(ijk, 16) = rk(ijk, 16) * att(ijk)
!
!
      if(azi(ijk).lt.0.D0)then
       STOP
      elseif(azi(ijk).ge. 0.00D+00 .and. azi(ijk).lt. 0.10D+02) then
       rk(ijk, 17)=-0.6650705923705481D-11
       rk(ijk, 17)=-0.6611929407629450D-09+(azi(ijk)- 0.00D+00) * rk(ijk, 17)
       rk(ijk, 17)= 0.0000000000000000D+00+(azi(ijk)- 0.00D+00) * rk(ijk, 17)
       rk(ijk, 17)= 0.3379090000000000D-05+(azi(ijk)- 0.00D+00) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.10D+02 .and. azi(ijk).lt. 0.20D+02) then
       rk(ijk, 17)= 0.5602117771116300D-11
       rk(ijk, 17)=-0.8607141184741096D-09+(azi(ijk)- 0.10D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.1521907059237054D-07+(azi(ijk)- 0.10D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.3306320000000000D-05+(azi(ijk)- 0.10D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.20D+02 .and. azi(ijk).lt. 0.30D+02) then
       rk(ijk, 17)= 0.2622234839240431D-11
       rk(ijk, 17)=-0.6926505853406212D-09+(azi(ijk)- 0.20D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.3075271763051785D-07+(azi(ijk)- 0.20D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.3073660000000000D-05+(azi(ijk)- 0.20D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.30D+02 .and. azi(ijk).lt. 0.40D+02) then
       rk(ijk, 17)= 0.6018942871922335D-11
       rk(ijk, 17)=-0.6139835401634082D-09+(azi(ijk)- 0.30D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.4381905888555813D-07+(azi(ijk)- 0.30D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.2699490000000000D-05+(azi(ijk)- 0.30D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.40D+02 .and. azi(ijk).lt. 0.50D+02) then
       rk(ijk, 17)= 0.9631993673069305D-11
       rk(ijk, 17)=-0.4334152540057376D-09+(azi(ijk)- 0.40D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.5429304682724960D-07+(azi(ijk)- 0.40D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.2205920000000000D-05+(azi(ijk)- 0.40D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.50D+02 .and. azi(ijk).lt. 0.60D+02) then
       rk(ijk, 17)= 0.1346308243579950D-10
       rk(ijk, 17)=-0.1444554438136391D-09+(azi(ijk)- 0.50D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.6007175380544358D-07+(azi(ijk)- 0.50D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.1629280000000000D-05+(azi(ijk)- 0.50D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.60D+02 .and. azi(ijk).lt. 0.70D+02) then
       rk(ijk, 17)= 0.2754267658372233D-10
       rk(ijk, 17)= 0.2594370292603067D-09+(azi(ijk)- 0.60D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.5892193795097616D-07+(azi(ijk)- 0.60D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.1027580000000000D-05+(azi(ijk)- 0.60D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.70D+02 .and. azi(ijk).lt. 0.78D+02) then
       rk(ijk, 17)= 0.3078605882445887D-11
       rk(ijk, 17)= 0.1085717326771811D-08+(azi(ijk)- 0.70D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.4547039439065438D-07+(azi(ijk)- 0.70D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.4918470000000000D-06+(azi(ijk)- 0.70D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.78D+02 .and. azi(ijk).lt. 0.86D+02) then
       rk(ijk, 17)=-0.2153154079283945D-10
       rk(ijk, 17)= 0.1159603867951960D-08+(azi(ijk)- 0.78D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.2750782483287821D-07+(azi(ijk)- 0.78D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.1991460000000000D-06+(azi(ijk)- 0.78D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge. 0.86D+02 .and. azi(ijk).lt. 0.90D+02) then
       rk(ijk, 17)= 0.1655300763843049D-09
       rk(ijk, 17)= 0.6428468889180169D-09+(azi(ijk)- 0.86D+02) * rk(ijk, 17)
       rk(ijk, 17)=-0.1308821877783924D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 17)
       rk(ijk, 17)= 0.4227390000000000D-07+(azi(ijk)- 0.86D+02) * rk(ijk, 17)
      elseif(azi(ijk).ge.90.D0)then
       rk(ijk, 17)= 0.1080050000000000D-07
      endif
      rk(ijk, 17) = rk(ijk, 17) * att(ijk)
!
      rk(ijk, 18) = SumM(ijk) * 6.0d-34 * (temp(ijk)/3.d2) ** (-2.3d0)
      rk(ijk, 18) = rk(ijk, 18) * SumM(ijk) * 0.2d0
      rk(ijk, 19) =  DEXP(-0.2555157957424871D+02   &
         - (  0.2060000000000000D+04 )/temp(ijk))
      rk(ijk, 20) =  DEXP(-0.2474064935803238D+02   &
         - ( -0.1100000000000000D+03 )/temp(ijk))
      rk(ijk, 20) = rk(ijk, 20) * SumM(ijk) * 0.8d0
      rk(ijk, 21) =  DEXP(-0.2416528521312882D+02   &
         - ( -0.7000000000000000D+02 )/temp(ijk))
      rk(ijk, 21) = rk(ijk, 21) * SumM(ijk) * 0.2d0
      rk(ijk, 22) =  0.2200000000000000D-09
      rk(ijk, 22) = rk(ijk, 22) * YlH2O(ijk)
      rk(ijk, 23) =  DEXP(-0.2716101748668281D+02   &
         - (  0.9400000000000000D+03 )/temp(ijk))
      rk(ijk, 24) =  DEXP(-0.3214088112211231D+02   &
         - (  0.5000000000000000D+03 )/temp(ijk))
      rk(ijk, 25) =  DEXP(-0.2375982010502066D+02   &
         - ( -0.2500000000000000D+03 )/temp(ijk))
      rk(ijk, 26) =  DEXP(-0.2656631037893612D+02   &
         - (  0.1600000000000000D+03 )/temp(ijk))
      rk(ijk, 27) = 2.2d-13 * dexp(620.0d0 / temp(ijk))   &
                    + 1.9d-33* SumM(ijk) * dexp(980.0d0 / temp(ijk))
      rk(ijk, 28) = 3.08d-34 * dexp(2820.0d0 / temp(ijk)) +    &
                    2.66d-54 * SumM(ijk) * dexp(3180.0d0 / temp(ijk))
      rk(ijk, 28) = rk(ijk, 28) * YlH2O(ijk)
      Effko(ijk) =  0.9000000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.1500000000000000D+01))
      Rapk(ijk) =  0.3000000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.0000000000000000D+00))
      rk(ijk, 29) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 30) =  DEXP(-0.2575921893902696D+02   &
         - ( -0.1200000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.9000000000000000D-31* (temp(ijk) / 3.d2)   &
                   **(- ( 0.2000000000000000D+01))
      Rapk(ijk) =  0.2200000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.0000000000000000D+00))
      rk(ijk, 31) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      Effko(ijk) =  0.7000000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.2600000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.5000000000000000D+00))
      rk(ijk, 32) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      Effko(ijk) =  0.2600000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.2400000000000000D-10* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1300000000000000D+01))
      rk(ijk, 33) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 34) =  0.2200000000000000D-10
      rk(ijk, 35) =  DEXP(-0.2632268829627837D+02   &
         - ( -0.2500000000000000D+03 )/temp(ijk))
      Effko(ijk) =  0.1800000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.4700000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1400000000000000D+01))
      rk(ijk, 36) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 37) =  DEXP( 0.6142746008608852D+02   &
         - (  0.1090000000000000D+05 )/temp(ijk))
      Effko(ijk) =  0.1800000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3200000000000000D+01))
      Rapk(ijk) =  0.4700000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1400000000000000D+01))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 37) = facteur(ijk) * rk(ijk, 37)
      rk(ijk, 38) =  0.3500000000000000D-11
      rk(ijk, 39) =  DEXP(-0.2474064935803238D+02   &
         - (  0.3900000000000000D+03 )/temp(ijk))
      Effko(ijk) = 7.2d-15 * dexp(785.0d0 / temp(ijk))
      Rapk(ijk) = 4.1d-16 * dexp(1440.0d0 / temp(ijk))
      facteur(ijk) =1.9d-33 * dexp(725.0d0 / temp(ijk)) * SumM(ijk)
      rk(ijk, 40) = Effko(ijk) + facteur(ijk)/(1.0d0 + facteur(ijk) / Rapk(ijk))
      rk(ijk, 41) =  DEXP(-0.2736865685146106D+02   &
         - ( -0.3800000000000000D+03 )/temp(ijk))
      rk(ijk, 42) =  DEXP(-0.2693787393536860D+02   &
         - (  0.1400000000000000D+04 )/temp(ijk))
      rk(ijk, 43) =  DEXP(-0.2975128465212864D+02   &
         - (  0.2450000000000000D+04 )/temp(ijk))
      rk(ijk, 44) =  0.3300000000000000D-38
      rk(ijk, 44) = rk(ijk, 44) * SumM(ijk) * 0.2d0
      rk(ijk, 45) =  DEXP(-0.2492297091482634D+02   &
         - ( -0.1700000000000000D+03 )/temp(ijk))
      rk(ijk, 46) =  DEXP(-0.3073211390514037D+02   &
         - (  0.1260000000000000D+04 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3900000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.7000000000000000D+00))
      rk(ijk, 47) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 48) =  DEXP( 0.6117554523749536D+02   &
         - (  0.1100000000000000D+05 )/temp(ijk))
      Effko(ijk) =  0.2200000000000000D-29* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3900000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.7000000000000000D+00))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 48) = facteur(ijk) * rk(ijk, 48)
      rk(ijk, 49) =  DEXP(-0.2779354004542632D+02   &
         - (  0.2450000000000000D+04 )/temp(ijk))
      rk(ijk, 50) =  DEXP(-0.2592627302369012D+02   &
         - (  0.2000000000000000D+04 )/temp(ijk))
      rk(ijk, 50) = rk(ijk, 50) * SumM(ijk) * 5.8d-7
      Effko(ijk) =  0.3000000000000000D-30* (temp(ijk) / 3.d2)   &
                   **(- ( 0.3300000000000000D+01))
      Rapk(ijk) =  0.1500000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.0000000000000000D+00))
      rk(ijk, 51) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.6000D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 52) = 1.5d-13 * (1.0d0 + 2.439d-20 * SumM(ijk))
      rk(ijk, 53) =  0.6000000000000000D-10
      rk(ijk, 54) =  0.0000000000000000D+00
      rk(ijk, 55) =  DEXP(-0.3943966082504782D+02   &
        + ( 0.2000000000000000D+01 * LOG(temp(ijk)))   &
        -  0.1361000000000000D+04/temp(ijk))
      rk(ijk, 56) =  DEXP(-0.3873183693007194D+02   &
        + ( 0.2000000000000000D+01 * LOG(temp(ijk)))   &
        -  0.4920000000000000D+03/temp(ijk))
      rk(ijk, 57) =   0.3760000000000000D-11   &
         * DEXP(-(  0.2600000000000000D+03 )/temp(ijk)) + & 
                 0.1700000000000000D-11   &
         * DEXP(-(  0.1550000000000000D+03 )/temp(ijk)) + & 
                 0.1210000000000000D-11   &
         * DEXP(-(  0.1250000000000000D+03 )/temp(ijk))
      rk(ijk, 58) =   0.1780000000000000D-11   &
         * DEXP(-( -0.4380000000000000D+03 )/temp(ijk)) + & 
                 0.6070000000000000D-12   &
         * DEXP(-( -0.5000000000000000D+03 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-( -0.4480000000000000D+03 )/temp(ijk))
      rk(ijk, 59) =  0.2540000000000000D-10   &
         * DEXP(-( -0.4100000000000000D+03 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-( -0.4400000000000000D+03 )/temp(ijk))
      rk(ijk, 60) =  0.3310000000000000D-11   &
        * DEXP(-( -0.3550000000000000D+03 )/temp(ijk)) + & 
                 0.3450000000000000D-12
      rk(ijk, 61) =  0.9999999999999999D-11
      rk(ijk, 62) =  DEXP(-0.2591722318817020D+02   &
         - ( -0.3310000000000000D+03 )/temp(ijk))
      rk(ijk, 63) =  DEXP(-0.3970958044115977D+02   &
        + ( 0.2000000000000000D+01 * LOG(temp(ijk)))   &
        +  0.9200000000000000D+02/temp(ijk))
      rk(ijk, 64) =  0.1860000000000000D-11   &
        * DEXP(-( -0.1750000000000000D+03 )/temp(ijk)) + & 
                 0.1320000000000000D-10
      rk(ijk, 65) =  DEXP(-0.2655601869289957D+02   &
         - ( -0.1900000000000000D+03 )/temp(ijk))
      rk(ijk, 66) =  DEXP(-0.2641908014195344D+02   &
         - ( -0.1900000000000000D+03 )/temp(ijk))
      rk(ijk, 67) =  0.1590000000000000D-13   &
        * DEXP(-( -0.5000000000000000D+03 )/temp(ijk)) + & 
                 0.3800000000000000D-13
      rk(ijk, 68) =  DEXP(-0.2596142928067470D+02   &
         - (  0.2600000000000000D+03 )/temp(ijk))
      rk(ijk, 69) =  DEXP(-0.2870983077730048D+02   &
         - (  0.1900000000000000D+04 )/temp(ijk))
      rk(ijk, 70) =  DEXP(-0.2729454887930734D+02   &
         - (  0.1900000000000000D+04 )/temp(ijk))
      rk(ijk, 71) =   0.1620000000000000D-11   &
         * DEXP(-(  0.1900000000000000D+04 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-(  0.1500000000000000D+03 )/temp(ijk)) + & 
                 0.1940000000000000D-13   &
         * DEXP(-(  0.1000000000000000D+04 )/temp(ijk))
      rk(ijk, 72) =  0.4920000000000000D-15
      rk(ijk, 73) =  0.4350000000000000D-17   &
         * DEXP( 0.2000000000000000D+01 * LOG(temp(ijk))   &
        -  0.2282000000000000D+04/temp(ijk)) + & 
                 0.1910000000000000D-13   &
         * DEXP(-(  0.4500000000000000D+03 )/temp(ijk)) + & 
                 0.1080000000000000D-14   &
         * DEXP(-( -0.4500000000000000D+03 )/temp(ijk)) + & 
                 0.0000000000000000D+00
      rk(ijk, 74) =  0.4000000000000000D-11   &
         * DEXP(-(  0.4460000000000000D+03 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-( -0.4900000000000000D+03 )/temp(ijk))
      rk(ijk, 75) =  DEXP(-0.3551694253050293D+02   &
         - (  0.5000000000000000D+03 )/temp(ijk))
      rk(ijk, 76) =  0.8170000000000000D-14   &
         * DEXP(-(  0.2580000000000000D+04 )/temp(ijk)) + & 
                 0.4320000000000000D-15   &
         * DEXP(-(  0.1800000000000000D+04 )/temp(ijk)) + & 
                 0.2870000000000000D-16   &
         * DEXP(-(  0.8450000000000000D+03 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-(  0.2283000000000000D+04 )/temp(ijk))
      rk(ijk, 77) =  0.7860000000000001D-14   &
         * DEXP(-(  0.1913000000000000D+04 )/temp(ijk)) + & 
                 0.0000000000000000D+00   &
         * DEXP(-(  0.7320000000000000D+03 )/temp(ijk))
      rk(ijk, 78) =  0.0000000000000000D+00   &
        * DEXP(-(  0.2112000000000000D+04 )/temp(ijk)) + & 
                 0.1380000000000000D-18
      rk(ijk, 79) =  DEXP(-0.3716986555487676D+02   &
         - (  0.1700000000000000D+04 )/temp(ijk))
      rk(ijk, 80) =  0.2000000000000000D-10
      rk(ijk, 81) =  0.9999999999999999D-11
      rk(ijk, 82) =  0.3600000000000000D-10
      rk(ijk, 83) =  DEXP(-0.3863712897853033D+02   &
         - ( -0.1044000000000000D+04 )/temp(ijk))
      rk(ijk, 83) = rk(ijk, 83) * SumM(ijk) * 0.2d0
      rk(ijk, 84) =  0.2800000000000000D-10
      Effko(ijk) =  0.9700000000000000D-28* (temp(ijk) / 3.d2)   &
                   **(- ( 0.5600000000000000D+01))
      Rapk(ijk) =  0.9300000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1500000000000000D+01))
      rk(ijk, 85) = (Effko(ijk) * SumM(ijk) /    &
                    ( 1.0d0 + Effko(ijk) * SumM(ijk) / Rapk(ijk))) *   &
                    0.5860D+00** (1.0d0 / (1.0d0 +    &
                     (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 86) =  DEXP( 0.6462080260895155D+02   &
         - (  0.1395400000000000D+05 )/temp(ijk))
      Effko(ijk) =  0.9700000000000000D-28* (temp(ijk) / 3.d2)   &
                   **(- ( 0.5600000000000000D+01))
      Rapk(ijk) =  0.9300000000000000D-11* (temp(ijk) / 3.d2)   &
                    **(- ( 0.1500000000000000D+01))
      facteur(ijk) = (Effko(ijk) * SumM(ijk) / ( 1.0d0 + Effko(ijk) * SumM(ijk) /    &
                 Rapk(ijk))) * 0.6d0 ** (1.0d0 / (1.0d0 +    &
                  (LOG10(Effko(ijk) * SumM(ijk) / Rapk(ijk)))**2))
      rk(ijk, 86) = facteur(ijk) * rk(ijk, 86)
      rk(ijk, 87) =  DEXP(-0.2619593659063922D+02   &
         - ( -0.1800000000000000D+03 )/temp(ijk))
      rk(ijk, 88) =  0.4360000000000000D-11
      rk(ijk, 89) =  0.6930000000000000D-11
      rk(ijk, 90) =  0.4000000000000000D-11
      rk(ijk, 91) =  0.4000000000000000D-11
      rk(ijk, 92) =  0.1220000000000000D-10
      rk(ijk, 93) =  0.4000000000000000D-11
      rk(ijk, 94) =  DEXP(-0.2859860514219026D+02   &
         - ( -0.8000000000000000D+03 )/temp(ijk))
      rk(ijk, 95) =  0.6160000000000000D-13   &
         * DEXP(-( -0.7000000000000000D+03 )/temp(ijk)) + & 
                 0.1520000000000000D-12   &
         * DEXP(-( -0.1300000000000000D+04 )/temp(ijk))
      rk(ijk, 96) =  DEXP(-0.2934027936364486D+02   &
         - ( -0.1300000000000000D+04 )/temp(ijk))
      rk(ijk, 98) =  DEXP(-0.2861185036894027D+02   &
         - ( -0.9800000000000000D+03 )/temp(ijk))
      rk(ijk, 99) =   0.5940000000000000D-12   &
         * DEXP(-( -0.5500000000000000D+03 )/temp(ijk)) + & 
                 0.1990000000000000D-15   &
         * DEXP(-( -0.2640000000000000D+04 )/temp(ijk)) + & 
                 0.5560000000000000D-13   &
         * DEXP(-( -0.1300000000000000D+04 )/temp(ijk))
      rk(ijk,100) =  DEXP(-0.2942678860655414D+02   &
         - ( -0.1300000000000000D+04 )/temp(ijk))
      rk(ijk,101) =  DEXP(-0.3002791688839384D+02   &
         - ( -0.4160000000000000D+03 )/temp(ijk))
      rk(ijk,102) =  0.1030000000000000D-13   &
         * DEXP(-( -0.1580000000000000D+03 )/temp(ijk)) + & 
                 0.6240000000000000D-13   &
         * DEXP(-( -0.4310000000000000D+03 )/temp(ijk)) + & 
                 0.1530000000000000D-13   &
         * DEXP(-( -0.4670000000000000D+03 )/temp(ijk)) + & 
                 0.4340000000000000D-14   &
         * DEXP(-( -0.6330000000000000D+03 )/temp(ijk))
      rk(ijk,103) =  DEXP(-0.2948253058956238D+02   &
         - ( -0.7080000000000000D+03 )/temp(ijk))
      rk(ijk,104) =  DEXP(-0.2962612150917463D+02   &
         - ( -0.7080000000000000D+03 )/temp(ijk))
      rk(ijk,105) =  DEXP(-0.3096643075705270D+02   &
         - ( -0.7080000000000000D+03 )/temp(ijk))
      rk(ijk,106) =   0.1770000000000000D-10   &
         * DEXP(-(  0.4400000000000000D+03 )/temp(ijk)) + & 
                 0.1480000000000000D-15   &
         * DEXP(-( -0.2510000000000000D+04 )/temp(ijk)) + & 
                 0.3100000000000000D-12   &
         * DEXP(-( -0.5080000000000000D+03 )/temp(ijk))
      rk(ijk,107) =  DEXP(-0.2982027752361559D+02   &
         - ( -0.7080000000000000D+03 )/temp(ijk))
      rk(ijk,108) =  0.4440000000000000D-13   &
         * DEXP(-( -0.2110000000000000D+03 )/temp(ijk)) + & 
                 0.2230000000000000D-12   &
         * DEXP(-( -0.4600000000000000D+03 )/temp(ijk)) + & 
                 0.4100000000000000D-13   &
         * DEXP(-( -0.5220000000000000D+03 )/temp(ijk)) + & 
                 0.1170000000000000D-13   &
         * DEXP(-( -0.6830000000000000D+03 )/temp(ijk))
      rk(ijk,109) =  DEXP(-0.2846113415156165D+02   &
         - ( -0.7650000000000000D+03 )/temp(ijk))
      rk(ijk,110) =  DEXP(-0.2790545796163031D+02   &
         - ( -0.7650000000000000D+03 )/temp(ijk))
      rk(ijk,111) =  DEXP(-0.2864437356064584D+02   &
         - ( -0.7650000000000000D+03 )/temp(ijk))
      rk(ijk,112) =  0.7730000000000000D-12   &
         * DEXP(-( -0.5300000000000000D+03 )/temp(ijk)) + & 
                 0.1700000000000000D-12   &
         * DEXP(-( -0.5650000000000000D+03 )/temp(ijk))
      rk(ijk,113) =  DEXP(-0.2835462750397320D+02   &
         - ( -0.7650000000000000D+03 )/temp(ijk))
      rk(ijk,114) =  DEXP(-0.3310607566097664D+02   &
         - ( -0.1000000000000000D+04 )/temp(ijk))
      rk(ijk,115) =  DEXP(-0.3132793274173975D+02   &
         - ( -0.1000000000000000D+04 )/temp(ijk))
      rk(ijk,116) =  0.1200000000000000D-11
      rk(ijk,117) =  0.1200000000000000D-11
      rk(ijk,118) =  0.1200000000000000D-11
      rk(ijk,119) =  0.1200000000000000D-11
      rk(ijk,120) =  0.1200000000000000D-11
      rk(ijk,121) =  0.3480000000000000D-11
      rk(ijk,122) =  0.1200000000000000D-11
      rk(ijk,123) =  DEXP(-0.2942678860655414D+02   &
         - ( -0.1300000000000000D+04 )/temp(ijk))
      rk(ijk,124) =  DEXP(-0.3274868498278332D+02   &
         - ( -0.1510000000000000D+04 )/temp(ijk))
      rk(ijk,125) =  DEXP(-0.3171146277298166D+02   &
         - ( -0.1560000000000000D+04 )/temp(ijk))
      rk(ijk,126) =  DEXP(-0.3717963534647257D+02   &
         - ( -0.2950000000000000D+04 )/temp(ijk))
      rk(ijk,127) =  0.4000000000000000D-11
      rk(ijk,128) =  0.1200000000000000D-11
       END DO
 
   END SUBROUTINE kinetic
 
  END MODULE mod_chem_spack_kinetic
 
